spring:
  application:
    name: linkd
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/linkd
    username: linkd
    password: linkd

  jpa:
    hibernate:
      ddl-auto: validate
  open-in-view: false

logging:
  level:
    root: DEBUG
    org.springframework.boot.context.config: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
config:
  base-url: "http://localhost:8080/api/v1/"
  chars: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_"
  base: 64
  length: 8
  scramble-number-pos: 6364136223846793005
  scramble-number-neg: -4576744217476464767
  default-expires-at: "2099-12-31T23:59:59Z"
  long-url-index: long_url_unique
  cache:
    ttl: 60
  lock_prefix: "lock:"
  lock_ttl_seconds: 5
  lock_poll_interval_ms: 50
  lock_max_wait_ms: 150
  redis_unlock_script: "if redis.call('get', KEYS[1]) == ARGV[1] then return redis.call('del', KEYS[1]) else return 0 end"
  creation_transaction_seconds: 3
  idempotency_lease_seconds: 5
  idempotency_retention_seconds: 86400
  idempotency_max_wait_ms: 1000
  idempotency_poll_interval_ms: 200

rate_limiter:
  capacity: 2
  refill_tokens: 1
  refill_period_nanos: 500_000_000_000 #5000 sec
  eviction_period_seconds: 60
  enabled: false