--use database linkd;
--CREATE TABLE links (
--    id SERIAL PRIMARY KEY,
--    short_code VARCHAR(10) NOT NULL,
--    long_url VARCHAR(200) NOT NULL,
--    created_at TIMESTAMP  NOT NULL,
--    BIGINT ttl;
--)

CREATE TABLE public.links (
	created_at timestamptz(6) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	short_code varchar(16) NOT NULL,
	long_url varchar(255) NOT NULL,
	ttl int8,
	CONSTRAINT links_pkey PRIMARY KEY (id),
	CONSTRAINT links_short_code_key UNIQUE (short_code)
);