ALTER TABLE links ALTER COLUMN id DROP IDENTITY IF EXISTS;

CREATE SEQUENCE IF NOT EXISTS links_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START WITH 1
    CACHE 1
    NO CYCLE;

SELECT setval('links_id_seq', COALESCE((SELECT MAX(id) FROM links), 0) + 1, false);

ALTER TABLE links ALTER COLUMN id SET DEFAULT nextval('links_id_seq');
